version: "3.9"
services:
    
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports: 
            - "1433:1433"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
    storage: 
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
            - "10000:10000"
    